# Generated by Django 5.2.4 on 2025-08-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_passwordresettoken_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='representative_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='representative_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
