# Generated by Django 5.2.4 on 2025-07-22 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobapplication_status'),
        ('notifications', '0002_message_messagethread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='notifications.messagethread'),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='thread_type',
            field=models.CharField(default='direct', max_length=50),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'recipient', 'created_at'], name='notificatio_sender__60341f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'read'], name='notificatio_recipie_197846_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'delivered'], name='notificatio_recipie_50a908_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread'], name='notificatio_thread__2afdb1_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['updated_at'], name='notificatio_updated_7d9786_idx'),
        ),
    ]
