# Generated by Django 5.2.4 on 2025-08-08 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0007_candidateverification_hospitalverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('terminated', 'Terminated'), ('resigned', 'Resigned'), ('completed', 'Completed')], default='active', max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employment_type', models.CharField(default='permanent', max_length=50)),
                ('performance_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_employments', to='profiles.candidateprofile')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_employees', to='profiles.recruiterprofile')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='profiles.hospital')),
            ],
            options={
                'unique_together': {('employee', 'employer', 'job_title', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='EmployeePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('monthly', 'Monthly Review'), ('quarterly', 'Quarterly Review'), ('annual', 'Annual Review'), ('project', 'Project Review')], max_length=20)),
                ('review_date', models.DateField()),
                ('technical_skills', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('communication', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('teamwork', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('punctuality', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('professionalism', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('overall_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('comments', models.TextField()),
                ('improvement_areas', models.TextField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_reviews', to=settings.AUTH_USER_MODEL)),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='employee_management.employment')),
            ],
        ),
        migrations.CreateModel(
            name='AbsenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_type', models.CharField(choices=[('sick_leave', 'Sick Leave'), ('personal_leave', 'Personal Leave'), ('vacation', 'Vacation'), ('emergency', 'Emergency'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_absences', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_requests', to=settings.AUTH_USER_MODEL)),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_requests', to='employee_management.employment')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning Shift'), ('evening', 'Evening Shift'), ('night', 'Night Shift'), ('full_day', 'Full Day')], default='full_day', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('busy', 'Busy'), ('on_leave', 'On Leave')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='employee_management.employment')),
            ],
            options={
                'unique_together': {('employment', 'date', 'shift')},
            },
        ),
    ]
