# Generated by Django 5.2.4 on 2025-07-21 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('jobs', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencenotification',
            name='active_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_notifications', to='jobs.activejob'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='profiles.candidateprofile'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='profiles.candidateprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('profile', 'job', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together={('profile', 'job', 'month', 'year')},
        ),
    ]
