# Generated by Django 5.2.4 on 2025-07-21 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CandidateFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_feedbacks', to='jobs.activejob')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_feedbacks', to='testimonials.feedbackcategory')),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_feedbacks', to='jobs.activejob')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_feedbacks', to='testimonials.feedbackcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('end_of_shift', 'End of Shift'), ('end_of_job', 'End of Job'), ('periodic', 'Periodic Review'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='jobs.activejob')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='jobs.job')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='profiles.candidateprofile')),
            ],
        ),
    ]
