# Generated by Django 5.2.4 on 2025-07-21 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('joining_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('competence_score', models.PositiveIntegerField(blank=True, null=True)),
                ('ethics_score', models.PositiveIntegerField(blank=True, null=True)),
                ('teamwork_score', models.PositiveIntegerField(blank=True, null=True)),
                ('conduct_score', models.PositiveIntegerField(blank=True, null=True)),
                ('overall_score', models.PositiveIntegerField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_employees', to='profiles.recruiterprofile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_jobs', to='profiles.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('locum', 'Locum')], max_length=20)),
                ('shift_start_time', models.TimeField(blank=True, null=True)),
                ('shift_end_time', models.TimeField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_unit', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('per_shift', 'Per Shift')], max_length=20)),
                ('experience_required', models.PositiveIntegerField(default=0)),
                ('is_filled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_fill_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='profiles.recruiterprofile')),
                ('required_qualifications', models.ManyToManyField(blank=True, to='documents.qualificationmaster')),
                ('required_skills', models.ManyToManyField(blank=True, to='documents.skillmaster')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_resigned', models.BooleanField(default=False)),
                ('resign_reason', models.TextField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_jobs', to='profiles.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_employees', to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('selected', 'Selected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20)),
                ('personal_statement', models.TextField(blank=True, null=True)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('withdrawn', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='profiles.candidateprofile')),
            ],
            options={
                'unique_together': {('profile', 'job')},
            },
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matching_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('matched_on', models.DateTimeField(auto_now_add=True)),
                ('match_type', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], max_length=10)),
                ('shortlisted', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='profiles.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.job')),
            ],
            options={
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
