# Generated by Django 5.2.4 on 2025-07-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('in_review', 'In Review'), ('shortlisted', 'Shortlisted'), ('interviewed', 'Interviewed'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('selected', 'Selected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20),
        ),
    ]
