# Generated by Django 5.2.4 on 2025-07-24 12:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_location', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_department', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('locum', 'Locum'), ('any', 'Any')], default='any', max_length=20)),
                ('minimum_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remote_work', models.BooleanField(default=False)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('preferred_shift', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_preference', to='profiles.candidateprofile')),
            ],
        ),
    ] 