# Generated by Django 5.2.4 on 2025-07-23 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_jobpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiterprofile',
            old_name='primary_contact',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='verification_status',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('primary_contact', models.CharField(max_length=100)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_hospitals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to='profiles.hospital'),
        ),
    ]
