# Generated by Django 5.2.4 on 2025-07-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_primary_contact_recruiterprofile_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Years of industrial experience'),
        ),
    ]
