# Generated by Django 5.2.4 on 2025-07-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_candidateprofile_experience_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='additional_documents',
            field=models.FileField(blank=True, null=True, upload_to='hospital_docs/additional/'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='hospital_docs/address/'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='gst_proof',
            field=models.FileField(blank=True, null=True, upload_to='hospital_docs/gst/'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='registration_proof',
            field=models.FileField(blank=True, null=True, upload_to='hospital_docs/registration/'),
        ),
    ]
