# Generated by Django 5.2.4 on 2025-07-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_hospital_additional_documents_hospital_address_proof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='additional_documents',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='address_proof',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='gst_proof',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='primary_contact',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='registration_proof',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='verification_date',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='hospital',
            name='password',
            field=models.CharField(default='password', max_length=128),
            preserve_default=False,
        ),
    ]
