# Generated by Django 5.2.4 on 2025-07-30 15:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_hospital_additional_documents_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('qualification_certificates', models.FileField(upload_to='candidate_verification/qualifications/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpeg', 'jpg', 'png'])])),
                ('registration_certificate', models.FileField(upload_to='candidate_verification/registration/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpeg', 'jpg', 'png'])])),
                ('resume', models.FileField(upload_to='candidate_verification/resume/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpeg', 'jpg', 'png'])])),
                ('government_id', models.FileField(upload_to='candidate_verification/id/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpeg', 'jpg', 'png'])])),
                ('additional_certifications', models.FileField(blank=True, null=True, upload_to='candidate_verification/additional/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpeg', 'jpg', 'png'])])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_record', to='profiles.candidateprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_verification_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('official_contact_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('primary_contact_name', models.CharField(max_length=100)),
                ('primary_contact_phone', models.CharField(max_length=20)),
                ('primary_contact_email', models.EmailField(max_length=254)),
                ('registration_proof', models.FileField(upload_to='hospital_verification/registration/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpeg', 'jpg', 'png'])])),
                ('gst_certificate', models.FileField(blank=True, null=True, upload_to='hospital_verification/gst/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpeg', 'jpg', 'png'])])),
                ('is_nabh_certified', models.BooleanField(default=False)),
                ('nabh_certificate', models.FileField(blank=True, null=True, upload_to='hospital_verification/nabh/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpeg', 'jpg', 'png'])])),
                ('other_certificates', models.FileField(blank=True, null=True, upload_to='hospital_verification/other/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpeg', 'jpg', 'png'])])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_record', to='profiles.hospital')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_verification_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
