// API base URL
const API_BASE = 'http://127.0.0.1:8000/api';

const ENDPOINTS = {
  register: API_BASE + '/accounts/register/',
  login: API_BASE + '/accounts/login/',
  recruiterLogin: API_BASE + '/accounts/recruiter-login/',
  adminLogin: API_BASE + '/accounts/admin-login/',
  verifyEmail: API_BASE + '/accounts/verify-email/',
  profile: API_BASE + '/accounts/profile/',
  changePassword: API_BASE + '/accounts/change-password/',
  jobs: API_BASE + '/jobs/',
  jobApplications: jobId => API_BASE + `/jobs/${jobId}/applications/`,
  applications: API_BASE + '/jobs/applications/',
  applicationDetail: id => API_BASE + `/jobs/applications/${id}/`,
  jobMatches: API_BASE + '/jobs/matches/',
  activeJobs: API_BASE + '/jobs/active/',
  completedJobs: API_BASE + '/jobs/completed/',
  jobSearch: API_BASE + '/jobs/search/',
  advancedJobSearch: API_BASE + '/jobs/advanced-search/',
  candidateProfile: API_BASE + '/profiles/candidate/',
  recruiterProfile: API_BASE + '/profiles/recruiter/',
  verificationStatus: API_BASE + '/profiles/verification-status/',
  supportingDocuments: API_BASE + '/documents/supporting-documents/',
  licensures: API_BASE + '/documents/licensures/',
  qualifications: API_BASE + '/documents/qualifications/',
  skills: API_BASE + '/documents/skills/',
  qualificationMasters: API_BASE + '/documents/qualification-masters/',
  skillMasters: API_BASE + '/documents/skill-masters/',
  notifications: API_BASE + '/notifications/',
  markAllNotificationsRead: API_BASE + '/notifications/mark-all-read/',
  emailNotifications: API_BASE + '/notifications/emails/',
  notificationRooms: API_BASE + '/notifications/rooms/',
  notificationRoomDetail: id => API_BASE + `/notifications/rooms/${id}/`,
  notificationRoomMessages: id => API_BASE + `/notifications/rooms/${id}/messages/`,
  notificationRoomMarkRead: id => API_BASE + `/notifications/rooms/${id}/mark-read/`,
  directMessage: API_BASE + '/notifications/direct-message/',
  userPresence: API_BASE + '/notifications/presence/',
  contacts: API_BASE + '/notifications/contacts/',
  messagingRooms: API_BASE + '/messaging/rooms/',
  messagingRoomDetail: id => API_BASE + `/messaging/rooms/${id}/`,
  messagingRoomMessages: id => API_BASE + `/messaging/rooms/${id}/messages/`,
  messagingRoomMarkRead: id => API_BASE + `/messaging/rooms/${id}/mark-read/`,
  onlineStatus: API_BASE + '/messaging/online-status/',
  chatSummary: API_BASE + '/messaging/summary/',
  attendance: API_BASE + '/attendance/',
  attendanceDetail: id => API_BASE + `/attendance/${id}/`,
  absences: API_BASE + '/attendance/absences/',
  absenceDetail: id => API_BASE + `/attendance/absences/${id}/`,
  attendanceSummaries: API_BASE + '/attendance/summaries/',
  dashboardStats: API_BASE + '/admin/dashboard-stats/',
  recentActivity: API_BASE + '/admin/recent-activity/',
  users: API_BASE + '/admin/users/'
};
